name: .NET Core build and publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build ./EarablesBLE/EarablesBLE/EarablesBLE.csproj --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release ./EarablesBLE/EarablesBLE/EarablesBLE.csproj
    - name: Add private GitHub registry to NuGet
      run: dotnet nuget sources add -name "GPR" -source https://nuget.pkg.github.com/ichbinstudent/index.json -username ichbinstudent -password ${{ secrets.GITHUB_PACKAGE_TOKEN }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push EarablesBLE\bin\Release\*.nupkg -Source "GPR" -SkipDuplicate
